name: "TG Watch"
version: "1.1.0"
slug: "tgwatch"
description: "Watch Telegram channels and send webhook to HA when keyword is found"
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
hassio_api: false
homeassistant_api: true
map:
  - config:rw
options:
  api_id: 0
  api_hash: ""
  session_name: "ha_tg_watch"
  webhook_url: "http://homeassistant.local:8123/api/webhook/tg_watch"
  match_regex: ""
  skip_regex: ""
  ha_event_type: ""
  log_level: "INFO"
schema:
  api_id: int
  api_hash: str
  session_name: str
  string_session: str
  webhook_url: str
  keywords:
    - str
  channels:
    - str
  match_regex: str?
  skip_regex: str?
  ha_event_type: str?
  log_level: list(INFO|DEBUG|WARNING|ERROR|CRITICAL)